client_config_backend: settings
client_config:
  client_id: 1097204139140-4uo2iq3fdu4lr048gs0mm66p17g08o7e.apps.googleusercontent.com
  client_secret: g2B_nrEq72FX7QjteAr8kzSS

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
